python train.py sc \
    --report_to wandb \
    --run_name style_classification \
    --output_dir outputs \
    --evaluation_strategy epoch \
    --save_strategy epoch \
    --per_device_train_batch_size 256 \
    --per_device_eval_batch_size 256 \
    --lr_scheduler_type cosine \
    --learning_rate 3e-5 \
    --adam_beta2 0.98 \
    --adam_epsilon 1e-09 \
    --num_train_epochs 50.0 \
    --save_total_limit 5 \
    --seed 42 \
    --fp16 False \
    --warmup_steps 20000 \
    --remove_unused_columns False \
    --load_best_model_at_end True \
    --metric_for_best_model f1